// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        return windows;
      // case TargetPlatform.linux:
      //   return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCR0zyfyG5UcrJD89q8Wif6KLtD1WOQBO0',
    appId: '1:245668040106:web:d7ebd9ca06160e1e36efd3',
    messagingSenderId: '245668040106',
    projectId: 'mandaue-foam-ar-1',
    authDomain: 'mandaue-foam-ar-1.firebaseapp.com',
    databaseURL: 'https://mandaue-foam-ar-1-default-rtdb.firebaseio.com',
    storageBucket: 'mandaue-foam-ar-1.firebasestorage.app',
    measurementId: 'G-CGV7CXGHR0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXZTOX70xysOb3Cz_zlpSzFc-CiHenUPA',
    appId: '1:245668040106:android:e5c7f075086a66dc36efd3',
    messagingSenderId: '245668040106',
    projectId: 'mandaue-foam-ar-1',
    databaseURL: 'https://mandaue-foam-ar-1-default-rtdb.firebaseio.com',
    storageBucket: 'mandaue-foam-ar-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHcaF59yTb-zINrC4OBc4wYQDnJFFJ1z4',
    appId: '1:245668040106:ios:b2acbeab5384a91336efd3',
    messagingSenderId: '245668040106',
    projectId: 'mandaue-foam-ar-1',
    databaseURL: 'https://mandaue-foam-ar-1-default-rtdb.firebaseio.com',
    storageBucket: 'mandaue-foam-ar-1.firebasestorage.app',
    iosBundleId: 'com.example.ar3dViewer',
  );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'your-macos-api-key',
  //   appId: 'your-macos-app-id',
  //   messagingSenderId: 'your-macos-sender-id',
  //   projectId: 'your-macos-project-id',
  //   storageBucket: 'your-macos-project-id.appspot.com',
  // );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXZTOX70xysOb3Cz_zlpSzFc-CiHenUPA',
    appId: '1:245668040106:android:e5c7f075086a66dc36efd3',
    messagingSenderId: '245668040106',
    projectId: 'mandaue-foam-ar-1',
    storageBucket: 'mandaue-foam-ar-1.firebasestorage.app',
  );

  // static const FirebaseOptions linux = FirebaseOptions(
  //   apiKey: 'your-linux-api-key',
  //   appId: 'your-linux-app-id',
  //   messagingSenderId: 'your-linux-sender-id',
  //   projectId: 'your-linux-project-id',
  //   storageBucket: 'your-linux-project-id.appspot.com',
  // );
}
